production:
  encoding: utf8
  adapter: postgresql
  username: postgres
  database: production_naspr
  template: template0

development:
  encoding: utf8
  adapter: postgresql
  username: postgres
  database: development_naspr
  template: template0

test:
  encoding: utf8
  adapter: postgresql
  username: postgres
  database: test_naspr
  template: template0

cucumber:
  encoding: utf8
  adapter: postgresql
  username: postgres
  database: test_naspr
  template: template0
